
package Vista;

import java.awt.Color;

public class vistaHerramienta extends javax.swing.JFrame {

    public vistaHerramienta() {
         setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        //setIconImage(getIconImage());
        
    }
/*Icono del proyecyo
    @Override
    public Image getIconImage (){
        String ruta = System.getProperty("user.dir");
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(ruta+"/src/main/resources/img/mini.jpg"));
        return retValue;}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jdpEscritorio = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        redondear2 = new Modelo.Redondear();
        redondear3 = new Modelo.Redondear();
        jLabel3 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        btnVentas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        icon_v = new javax.swing.JLabel();
        btnInventario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        icon_i = new javax.swing.JLabel();
        btnTrabajadores = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        icon_t = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        icon_h = new javax.swing.JLabel();
        btnEditoriales = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        icon_p = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        salu2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 670));

        redondear1.setBackground(new java.awt.Color(0, 51, 102));
        redondear1.setPreferredSize(new java.awt.Dimension(1500, 660));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpEscritorio.setBackground(new java.awt.Color(39, 107, 162));
        jdpEscritorio.setRequestFocusEnabled(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horario.png"))); // NOI18N

        jdpEscritorio.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpEscritorioLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpEscritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        redondear1.add(jdpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 900, 600));

        redondear2.setBackground(new java.awt.Color(39, 107, 162));
        redondear2.setRoundBottomLeft(60);
        redondear2.setRoundTopLeft(60);
        redondear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redondear3.setBackground(new java.awt.Color(218, 150, 25));
        redondear3.setRoundBottomLeft(60);
        redondear3.setRoundBottomRight(60);
        redondear3.setRoundTopLeft(60);
        redondear3.setRoundTopRight(60);
        redondear3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setText("Bienvenido,");
        redondear3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 90, 30));
        redondear3.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 60));

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblNombres.setText("Diego");
        redondear3.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        lblApellidos.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblApellidos.setText("Bautista");
        redondear3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 20));

        lblDNI.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblDNI.setText("DNI:75792854");
        redondear3.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 20));

        redondear2.add(redondear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 230, 110));

        btnVentas.setBackground(new java.awt.Color(39, 107, 162));
        btnVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        btnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(218, 150, 25));
        jLabel10.setText("Ventas");
        btnVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));
        btnVentas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        icon_v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_ventas.png"))); // NOI18N
        icon_v.setAlignmentY(0.0F);
        btnVentas.add(icon_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        redondear2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, 40));

        btnInventario.setBackground(new java.awt.Color(39, 107, 162));
        btnInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        btnInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(218, 150, 25));
        jLabel8.setText("Inventario");
        btnInventario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 120, 40));
        btnInventario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        icon_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_inventario.png"))); // NOI18N
        btnInventario.add(icon_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        redondear2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 40));

        btnTrabajadores.setBackground(new java.awt.Color(39, 107, 162));
        btnTrabajadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        btnTrabajadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(218, 150, 25));
        jLabel12.setText("Trabajadores");
        btnTrabajadores.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 150, 40));
        btnTrabajadores.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        icon_t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_trabajador.png"))); // NOI18N
        btnTrabajadores.add(icon_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        redondear2.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 40));

        btnHistorial.setBackground(new java.awt.Color(39, 107, 162));
        btnHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        btnHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnHistorial.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(218, 150, 25));
        jLabel14.setText("Historial");
        btnHistorial.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 2, 100, 40));

        icon_h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_historial.png"))); // NOI18N
        btnHistorial.add(icon_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        redondear2.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 250, 40));

        btnEditoriales.setBackground(new java.awt.Color(39, 107, 162));
        btnEditoriales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        btnEditoriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(218, 150, 25));
        jLabel16.setText("Proveedores");
        btnEditoriales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, 40));
        btnEditoriales.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        icon_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_proveedor.png"))); // NOI18N
        btnEditoriales.add(icon_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        redondear2.add(btnEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 40));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 210, 129));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logosheyla.png"))); // NOI18N
        redondear2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 210));

        redondear1.add(redondear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 650));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        redondear1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 37, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        redondear1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 37, -1));
        redondear1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, 30));

        salu2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        salu2.setForeground(new java.awt.Color(189, 214, 233));
        salu2.setText("Bienvenido!!");
        redondear1.add(salu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, -1, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 214, 233));
        jLabel5.setText("Al Sistema de Ventas");
        redondear1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 494, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaHerramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JPanel btnEditoriales;
    public javax.swing.JPanel btnHistorial;
    public javax.swing.JPanel btnInventario;
    public javax.swing.JPanel btnTrabajadores;
    public javax.swing.JPanel btnVentas;
    private javax.swing.JLabel icon_h;
    private javax.swing.JLabel icon_i;
    private javax.swing.JLabel icon_p;
    private javax.swing.JLabel icon_t;
    private javax.swing.JLabel icon_v;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JDesktopPane jdpEscritorio;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblFoto;
    public javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblNombres;
    private Modelo.Redondear redondear1;
    private Modelo.Redondear redondear2;
    private Modelo.Redondear redondear3;
    private javax.swing.JLabel salu2;
    // End of variables declaration//GEN-END:variables
}
