/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Frank
 */
public class vistaEditoriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaVenta
     */
    public vistaEditoriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditoriales = new javax.swing.JTable();
        btnEliminar_Edit = new javax.swing.JButton();
        btnEditar_Edit = new javax.swing.JButton();
        btnAgregar_Edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre_editorial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPais_editorial = new javax.swing.JTextField();
        txtEmail_editorial = new javax.swing.JTextField();
        txtTelefono_editorial = new javax.swing.JTextField();
        txtAño_editorial = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnActualizar_Edit = new javax.swing.JButton();
        txtId_editorial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(870, 580));

        redondear1.setBackground(new java.awt.Color(27, 114, 159));
        redondear1.setForeground(new java.awt.Color(184, 184, 184));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 150, 25));
        jLabel1.setText("Proveedores");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        tblEditoriales.setBackground(new java.awt.Color(240, 244, 239));
        tblEditoriales.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PAIS", "TELEFONO", "EMAIL", "AÑO"
            }
        ));
        jScrollPane1.setViewportView(tblEditoriales);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 620, 390));

        btnEliminar_Edit.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar_Edit.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnEliminar_Edit.setText("ELIMINAR ");
        btnEliminar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnEliminar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnEliminar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 160, 50));

        btnEditar_Edit.setBackground(new java.awt.Color(51, 153, 255));
        btnEditar_Edit.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnEditar_Edit.setText("EDITAR");
        btnEditar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnEditar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnEditar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 160, 50));

        btnAgregar_Edit.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar_Edit.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnAgregar_Edit.setText("AGREGAR");
        btnAgregar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAgregar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnAgregar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, 50));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Proveedor");
        redondear1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, 220, -1));

        txtNombre_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtNombre_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtNombre_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre_editorial.setBorder(null);
        redondear1.add(txtNombre_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("País:");
        redondear1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        redondear1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono:");
        redondear1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, -1, 30));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");
        redondear1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Año:");
        redondear1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtPais_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtPais_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtPais_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtPais_editorial.setBorder(null);
        redondear1.add(txtPais_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 110, 30));

        txtEmail_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtEmail_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtEmail_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail_editorial.setBorder(null);
        redondear1.add(txtEmail_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 110, 30));

        txtTelefono_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtTelefono_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtTelefono_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono_editorial.setBorder(null);
        redondear1.add(txtTelefono_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 30));

        txtAño_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtAño_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtAño_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtAño_editorial.setBorder(null);
        redondear1.add(txtAño_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 110, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 20));

        jSeparator2.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, 20));

        jSeparator6.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 110, 20));

        jSeparator7.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 110, 20));

        jSeparator8.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 110, 20));

        jSeparator9.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 110, 20));

        btnActualizar_Edit.setBackground(new java.awt.Color(255, 204, 0));
        btnActualizar_Edit.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnActualizar_Edit.setText("ACTUALIZAR");
        btnActualizar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnActualizar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnActualizar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 180, 50));

        txtId_editorial.setBackground(new java.awt.Color(27, 114, 159));
        txtId_editorial.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtId_editorial.setForeground(new java.awt.Color(255, 255, 255));
        txtId_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_editorialActionPerformed(evt);
            }
        });
        redondear1.add(txtId_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 30));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre:");
        redondear1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar_EditActionPerformed

    private void btnEditar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar_EditActionPerformed

    private void btnAgregar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar_EditActionPerformed

    private void btnActualizar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar_EditActionPerformed

    private void txtId_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_editorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar_Edit;
    public javax.swing.JButton btnAgregar_Edit;
    public javax.swing.JButton btnEditar_Edit;
    public javax.swing.JButton btnEliminar_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private Modelo.Redondear redondear1;
    public javax.swing.JTable tblEditoriales;
    public javax.swing.JTextField txtAño_editorial;
    public javax.swing.JTextField txtEmail_editorial;
    public javax.swing.JTextField txtId_editorial;
    public javax.swing.JTextField txtNombre_editorial;
    public javax.swing.JTextField txtPais_editorial;
    public javax.swing.JTextField txtTelefono_editorial;
    // End of variables declaration//GEN-END:variables
}
