/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Dimension;

/**
 *
 * @author Frank
 */
public class vistaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInventario
     */public JDateChooser dateChooser;

    public vistaInventario() {
        initComponents();

// Agregar JDateChooser
dateChooser = new JDateChooser();
dateChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14)));
dateChooser.setDateFormatString("yyyy/MM/dd");

// Desactivar la edición directa del campo de texto para evitar problemas de formato
JTextFieldDateEditor editor = (JTextFieldDateEditor) dateChooser.getDateEditor();
editor.setEditable(false);
dateChooser.setPreferredSize(new Dimension(100,50));
jPanel1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, 30));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        txtSer = new javax.swing.JTextField();
        cbxEdit = new javax.swing.JComboBox<>();
        cbxRes = new javax.swing.JComboBox<>();
        spnNum = new javax.swing.JSpinner();
        cbxFor = new javax.swing.JComboBox<>();
        spnSto = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtPre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        redondear2 = new Modelo.Redondear();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();
        cbxAutor = new javax.swing.JComboBox<>();
        btnAgregarAutor = new javax.swing.JButton();
        btnEliminarAutor = new javax.swing.JButton();
        redondear3 = new Modelo.Redondear();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGeneros = new javax.swing.JTable();
        cbxGenero = new javax.swing.JComboBox<>();
        btnAgregarGenero = new javax.swing.JButton();
        btnEliminarGenero = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaSipnosis = new javax.swing.JTextArea();
        btnFoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redondear1.setBackground(new java.awt.Color(27, 114, 159));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 150, 25));
        jLabel1.setText("Control de Inventario");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -10, -1, -1));

        tblInventario.setBackground(new java.awt.Color(240, 244, 239));
        tblInventario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "EDITORIAL", "SERIE", "UBICACION", "RESTRICCION", "FORMATO", "NUMERO", "STOCK", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 720, 180));

        txtSer.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtSer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(txtSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 110, 60));

        cbxEdit.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        cbxEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editorial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(cbxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 60));

        cbxRes.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        cbxRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "T", "T+", "M" }));
        cbxRes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restricción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(cbxRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 60));

        spnNum.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Pag.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, 60));

        cbxFor.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        cbxFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tapa Dura", "Tapa Blanda" }));
        cbxFor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(cbxFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 60));

        spnSto.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnSto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ejemplares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(spnSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 120, 60));

        btnBuscar.setBackground(new java.awt.Color(27, 114, 159));
        btnBuscar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setBorder(null);
        redondear1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 30));

        txtUbi.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtUbi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ubicación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 110, 60));

        btnAgregar.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        redondear1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 120, 40));

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        redondear1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        redondear1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 120, 40));

        txtPre.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        txtPre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        redondear1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, 60));

        jSeparator1.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 20));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        redondear1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, -1, 50));

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        redondear1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 120, 40));

        redondear2.setBackground(new java.awt.Color(247, 210, 129));
        redondear2.setRoundBottomLeft(15);
        redondear2.setRoundBottomRight(15);
        redondear2.setRoundTopLeft(15);
        redondear2.setRoundTopRight(15);
        redondear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tblAutores);

        redondear2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 130));

        cbxAutor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 0, 14))); // NOI18N
        redondear2.add(cbxAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        btnAgregarAutor.setText("Agregar");
        redondear2.add(btnAgregarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));

        btnEliminarAutor.setText("Eliminar");
        btnEliminarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAutorActionPerformed(evt);
            }
        });
        redondear2.add(btnEliminarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 210, 80, 30));

        redondear1.add(redondear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 180, 250));

        redondear3.setBackground(new java.awt.Color(144, 39, 36));
        redondear3.setRoundBottomLeft(15);
        redondear3.setRoundBottomRight(15);
        redondear3.setRoundTopLeft(15);
        redondear3.setRoundTopRight(15);
        redondear3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGeneros.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        tblGeneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(tblGeneros);

        redondear3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 130));

        cbxGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Género", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 0, 14))); // NOI18N
        redondear3.add(cbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        btnAgregarGenero.setText("Agregar");
        redondear3.add(btnAgregarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));

        btnEliminarGenero.setText("Eliminar");
        redondear3.add(btnEliminarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        redondear1.add(redondear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 190, 250));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa un Titulo:");
        redondear1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txaSipnosis.setColumns(20);
        txaSipnosis.setRows(5);
        txaSipnosis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sipnosis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 0, 14))); // NOI18N
        jScrollPane4.setViewportView(txaSipnosis);

        redondear1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 90));

        btnFoto.setText("Selecciona tu Imagen");
        redondear1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 160, 30));

        jPanel1.setBackground(new java.awt.Color(27, 114, 159));
        redondear1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, 70));

        getContentPane().add(redondear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAgregarAutor;
    public javax.swing.JButton btnAgregarGenero;
    public javax.swing.JTextField btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminarAutor;
    public javax.swing.JButton btnEliminarGenero;
    public javax.swing.JButton btnFoto;
    public javax.swing.JComboBox<String> cbxAutor;
    public javax.swing.JComboBox<String> cbxEdit;
    public javax.swing.JComboBox<String> cbxFor;
    public javax.swing.JComboBox<String> cbxGenero;
    public javax.swing.JComboBox<String> cbxRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private Modelo.Redondear redondear1;
    private Modelo.Redondear redondear2;
    private Modelo.Redondear redondear3;
    public javax.swing.JSpinner spnNum;
    public javax.swing.JSpinner spnSto;
    public javax.swing.JTable tblAutores;
    public javax.swing.JTable tblGeneros;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTextArea txaSipnosis;
    public javax.swing.JTextField txtPre;
    public javax.swing.JTextField txtSer;
    public javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables
}
